// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg-dHwZF63cG67eLcG-psPlcsFRL5IeZ4',
    appId: '1:982763664170:web:ad25047b776eb21f64e453',
    messagingSenderId: '982763664170',
    projectId: 'luxewear-21f21',
    authDomain: 'luxewear-21f21.firebaseapp.com',
    storageBucket: 'luxewear-21f21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb90NH5gwJh7x6VsUETkL9aWgr0Ik5kSY',
    appId: '1:982763664170:android:0e4f0f85538816a064e453',
    messagingSenderId: '982763664170',
    projectId: 'luxewear-21f21',
    storageBucket: 'luxewear-21f21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY3YakJnb6SiHZmgsa-S7M_I4-zK_VqIo',
    appId: '1:982763664170:ios:3235720e7b06fbc664e453',
    messagingSenderId: '982763664170',
    projectId: 'luxewear-21f21',
    storageBucket: 'luxewear-21f21.firebasestorage.app',
    iosBundleId: 'com.example.firebaseflutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY3YakJnb6SiHZmgsa-S7M_I4-zK_VqIo',
    appId: '1:982763664170:ios:3235720e7b06fbc664e453',
    messagingSenderId: '982763664170',
    projectId: 'luxewear-21f21',
    storageBucket: 'luxewear-21f21.firebasestorage.app',
    iosBundleId: 'com.example.firebaseflutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg-dHwZF63cG67eLcG-psPlcsFRL5IeZ4',
    appId: '1:982763664170:web:3088556f24b21b6764e453',
    messagingSenderId: '982763664170',
    projectId: 'luxewear-21f21',
    authDomain: 'luxewear-21f21.firebaseapp.com',
    storageBucket: 'luxewear-21f21.firebasestorage.app',
  );
}
